Repository Refugee-Aid-Capstone/refugee_aid_be, pull requests merged in 2023-10, with the labels that each got.

#18 Heroku setup
  app.json
Labels: deployment

#19 Heroku setup
  Gemfile.lock
  Procfile
Labels: deployment

#23 feat: add some ci build language for heroku
  app.json
Labels: deployment

#22 17 organization seed data
  Gemfile
  Gemfile.lock
  db/seeds.rb
  spec/factories/organizations.rb
Labels: enhancement

#24 fix: add rand coord to ranged coord
  .gitignore
  db/seeds.rb
Labels: bug

#33 Update README.md
  README.md
Labels: documentation

#47 fix: fix CSV import bug, change organization boolean validations
  app/models/organization.rb
  db/seeds.rb
  spec/models/organization_spec.rb
Labels: bug

#63 fix: moved sprockets to development container
  Gemfile
  config/application.rb
Labels: bug
